#!/bin/sh

# Run backend tests
echo "===========[Running backend tests]==========="
cd backend
python3 -m unittest discover ./test

# Run frontend tests
echo "\n===========[Running frontend tests]==========="
cd ../frontend
npm run test

# Return to original directory
cd ..
